<a href="https://colab.research.google.com/github/jaekyoungkim/nlp_in_action/blob/main/%EC%9E%90%EC%97%B0%EC%96%B4_%EC%B2%98%EB%A6%AC_%EC%9D%B8_%EC%95%A1%EC%85%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/totalgood/nlpia

Cloning into 'nlpia'...
remote: Enumerating objects: 6365, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 6365 (delta 86), reused 132 (delta 55), pack-reused 6176
Receiving objects: 100% (6365/6365), 124.18 MiB | 26.38 MiB/s, done.
Resolving deltas: 100% (4033/4033), done.


In [ ]:
#

# ch01. 사고의 단위 : nlp개요 

In [21]:
# 정규식
import re  # regex/re 두개 있음 
r = "(hi|hello|hey)[ ] *([a-z]*)" # a-z에 포함하는 글자가 임의의 횟수로 나타날수 있음

In [4]:
re.match(r, "hello rosa", flags= re.IGNORECASE)


<re.Match object; span=(0, 10), match='hello rosa'>

In [5]:
re.match(r, "hi ho, hiho, it's off to work ...", flags= re.IGNORECASE) 


<re.Match object; span=(0, 5), match='hi ho'>

In [7]:
re.match(r, "hey what's up.", flags= re.IGNORECASE)  # 대소문자 구분 무시함


<re.Match object; span=(0, 8), match='hey what'>

In [31]:
# code error 
# r = r'[^a-z]*([y]o|[h']?ello|ok|hey|(good[ ])?(morn[gin']{0,3}|'\r'afternoon|even[gin']{0,3}))[\s.;:]{1,3}([a-z]{1,20})'
# r' : 정규 표현식 아니라 원시 문자열을 뜻함


In [22]:
re_greeting = re.compile(r, flags =re.IGNORECASE) # compile 메서드로 정규표현식을 미리 컴파일해두면 정규식을 적용할때마다 옵션을 지정할 필요 없음

In [23]:
re_greeting.match('Hello Rosa') 

<re.Match object; span=(0, 10), match='Hello Rosa'>

In [24]:
re_greeting.match('Good moring Rosa') 

In [25]:
re_greeting.match('good evening rosa parks')

In [30]:
my_names = set(['rosa','rose','chatty','chatbot','bot','chatterbot'])
curt_names = set(['hal','you','u']) 
greeter_name ='' #아직 챗봇은 대화상대가 누군지 모름
match = re_greeting.match(input())
if match:
  at_name = match.groups()[-1]
  if at_name in curt_names:
    print('good one')
  elif at_name.lower() in my_names: 
    print('hi {} how are you?'.format(greeter_name)) 


hello rosa
hi  how are you?


In [33]:
my_names = set(['rosa','rose','chatty','chatbot','bot','chatterbot'])
curt_names = set(['hal','you','u']) 
greeter_name ='' #아직 챗봇은 대화상대가 누군지 모름
match = re_greeting.match(input())
if match:
  at_name = match.groups()[-1]
  if at_name in curt_names:
    print('good one')
  elif at_name.lower() in my_names: 
    print('hi {} how are you?'.format(greeter_name)) 

hello you
good one


In [34]:
# 부록b의 정규식
# 프로그램 언어로 이루어진 하나의 작은 프로그램
# 문자열을  컴파일해서 하나의 작은 프로그램을 만들고 그것을 다른 문자열들에 대해 실행함으로써 패턴 부합을 수행
# | or
# () 그룹묶기
# [] 문자부류
# \s \b \d \w  흔히쓰이는 문자 부류들의 단축표기
# * ? + 반복횟수 지정
# {7,10} : 반복횟수를 좀더 구체적으로 지정


In [35]:
import re 
re.findall(r'Hannes|Hobson|Cole', 'Hobson lane, Cole Howard, and Hannes Max Hapke') 


['Hobson', 'Cole', 'Hannes']

In [38]:
re.findall(r'H|Hobson|Cole', 'Hobson lane, Cole Howard, and Hannes Max Hapke')

['H', 'Cole', 'H', 'H', 'H']

In [39]:
# () 그룹묶기
# r'(kitt|dogg)y
match = re.match(r'(kitt|dogg)y' , "doggy") 

In [40]:
match.group()

'doggy'

In [41]:
match.group(0)

'doggy'

In [42]:
match.groups()

('dogg',)

In [46]:
match = re.match(r'((kitt|dogg)(y))',  "doggy") # 괄호를 더 추가해서 전체 부합과 접미사도 개별적인 그룹으로 묶기


In [49]:
match.groups()

('doggy', 'dogg', 'y')

In [52]:
match.group(3)

'y'

In [53]:
# [ ] 문자부류
# [abcd] : a or b or c or d
# [a-d] : a-d
# [a-c1-3] : [abc123] 


In [55]:
from collections import Counter  # counter : 토큰들을 각각의 통으로 분류하고 그 개수를 세는 기능 제공 
Counter('guten morgen rosa'.split())

Counter({'guten': 1, 'morgen': 1, 'rosa': 1})

In [56]:
from itertools import permutations
[" ".join(combo) for combo in permutations("good morning rosa!".split(),3)]

['good morning rosa!',
 'good rosa! morning',
 'morning good rosa!',
 'morning rosa! good',
 'rosa! good morning',
 'rosa! morning good']

In [57]:
#  단어 순서가 중요한 좀더 길고 복잡한 문장
s = """find textbooks with titles containing nlp or natural and language or computational and linguistics."""
len(set(s.split()))

12

In [8]:
import numpy as np
np.arange(1, 12+1).prod()  # factorial(12)
# sapcy, syntaxnet: 자연어 문장에서 구문적, 놀리적 관계를 추출하게 해줌


479001600

In [ ]:
# 챗봇을 만들기 위한 알고리즘
# 1. 파싱 :텍스트에서 특징들과 구조적 수치자료를 추출
# 2. 분석 : 정서, 문법성, 으미론에 대한 평점
# 3. 생성 : 적절한 응답문 작성
# 4, 실행

# ch02. 나만의 어취 구축 : 단어 토큰화 

In [60]:
# 토큰 : 문자열을 개별적인 의미 단위들로 분할하는 방법을 적용한 단위 
# we'll -> we will로 구분할 수 있어야함
# 토큰생성기를 이용한 어휘구축
# 컴퓨터 언어로된 소스코드를 토크화하는데 쓰이는 토큰 생성기 :  스캐너, 렉서(lexical analyzer) 
# 어휘집 , 파서(컴파일러), 토큰, 용어, 단어, n그램 등의 용어들이 사용됨
# 토큰화는 구조가 없는 자료인 자연어 텍스트를 정보 조각들로 분할함


In [2]:
sentence = '''thomas jefferson began building monticello at the age of 26.'''
sentence.split()

['thomas',
 'jefferson',
 'began',
 'building',
 'monticello',
 'at',
 'the',
 'age',
 'of',
 '26.']

In [3]:
str.split(sentence)

['thomas',
 'jefferson',
 'began',
 'building',
 'monticello',
 'at',
 'the',
 'age',
 'of',
 '26.']

In [4]:
token_sequence = str.split(sentence)
vocab = sorted(set(token_sequence))
', '.join(vocab)

'26., age, at, began, building, jefferson, monticello, of, the, thomas'

In [5]:
num_tokens = len(token_sequence) ;num_tokens

10

In [6]:
vocab_size = len(vocab) ; vocab_size

10

In [10]:
onehot_vectors = np.zeros((num_tokens, vocab_size), int) ;onehot_vectors

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
for i , word in enumerate(token_sequence):
  onehot_vectors[i, vocab.index(word)] = 1
  

In [12]:
' '.join(vocab)

'26. age at began building jefferson monticello of the thomas'

In [13]:
onehot_vectors

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [14]:
import pandas as pd
pd.DataFrame(onehot_vectors, columns = vocab)

26.  age  at  began  building  jefferson  monticello  of  the  thomas
0    0    0   0      0         0          0           0   0    0       1
1    0    0   0      0         0          1           0   0    0       0
2    0    0   0      1         0          0           0   0    0       0
3    0    0   0      0         1          0           0   0    0       0
4    0    0   0      0         0          0           1   0    0       0
5    0    0   1      0         0          0           0   0    0       0
6    0    0   0      0         0          0           0   0    1       0
7    0    1   0      0         0          0           0   0    0       0
8    0    0   0      0         0          0           0   1    0       0
9    1    0   0      0         0          0           0   0    0       0

In [15]:
df = pd.DataFrame(onehot_vectors, columns = vocab)

In [16]:
df[df==0] = ''

In [17]:
df

26. age at began building jefferson monticello of the thomas
0                                                            1
1                                   1                         
2                1                                            
3                         1                                   
4                                              1              
5          1                                                  
6                                                     1       
7       1                                                     
8                                                 1           
9   1

In [18]:
# 장점은 어떤 정보도 소실되지 않지만 복원할때도 완벽함
# 원문의 모든 세부사항을 유지함, 컴퓨터가 이해할 수 있는 수치자료의 형태임
# 단어 모음 벡터(빈도벡터) : 단어의 순서 안나타나기때문에 복원 불가능

In [20]:
sentence_bow = {}
for token in sentence.split():
  sentence_bow[token] = 1
  sorted(sentence_bow.items())

In [21]:
sentence_bow

{'26.': 1,
 'age': 1,
 'at': 1,
 'began': 1,
 'building': 1,
 'jefferson': 1,
 'monticello': 1,
 'of': 1,
 'the': 1,
 'thomas': 1}

In [28]:
import pandas as pd
df = pd.DataFrame( pd.Series(dict([(token,1) for token in sentence.split()])), columns=['sent']).T

In [26]:
[(token,1) for token in sentence.split()]

[('thomas', 1),
 ('jefferson', 1),
 ('began', 1),
 ('building', 1),
 ('monticello', 1),
 ('at', 1),
 ('the', 1),
 ('age', 1),
 ('of', 1),
 ('26.', 1)]

In [29]:
df

thomas  jefferson  began  building  monticello  at  the  age  of  26.
sent       1          1      1         1           1   1    1    1   1    1

In [39]:
sentences = """thomas jefferson began building moticello at the age of 26.\n"""
sentences += """construction was done mostly by local masons and carpenters.\n"""
sentences += """he moved into the south pavilion in 1770.\n"""
sentences += """turning moticello into a neoclassical masterpiece was jefferson's obsession."""
corpus ={}
print(sentences)

thomas jefferson began building moticello at the age of 26.
construction was done mostly by local masons and carpenters.
he moved into the south pavilion in 1770.
turning moticello into a neoclassical masterpiece was jefferson's obsession.


In [41]:
for i, sent in enumerate(sentences.split('\n')):
  corpus['sent{}'.format(i)] = dict((tok,1) for tok in sent.split())

In [42]:
corpus

{'sent0': {'26.': 1,
  'age': 1,
  'at': 1,
  'began': 1,
  'building': 1,
  'jefferson': 1,
  'moticello': 1,
  'of': 1,
  'the': 1,
  'thomas': 1},
 'sent1': {'and': 1,
  'by': 1,
  'carpenters.': 1,
  'construction': 1,
  'done': 1,
  'local': 1,
  'masons': 1,
  'mostly': 1,
  'was': 1},
 'sent2': {'1770.': 1,
  'he': 1,
  'in': 1,
  'into': 1,
  'moved': 1,
  'pavilion': 1,
  'south': 1,
  'the': 1},
 'sent3': {'a': 1,
  'into': 1,
  "jefferson's": 1,
  'masterpiece': 1,
  'moticello': 1,
  'neoclassical': 1,
  'obsession.': 1,
  'turning': 1,
  'was': 1}}

In [35]:
df =pd.DataFrame.from_records(corpus).fillna(0).astype(int).T
df[df.columns[:10]]

thomas  jefferson  began  building  moticello  at  the  age  of  26.
sent0       1          1      1         1          1   1    1    1   1    1
sent1       0          0      0         0          0   0    0    0   0    0
sent2       0          0      0         0          0   0    1    0   0    0
sent3       0          0      0         0          1   0    0    0   0    0

In [43]:
# 내적
v1 = pd.np.array([1,2,3]) 
v2 = pd.np.array([2,3,4]) 
(v1*v2).sum() # 굉장히 효율적인 계산

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  This is separate from the ipykernel package so we can avoid doing imports until


20

In [50]:
sum([x1 * x2 for x1, x2 in zip(v1,v2)])

20

In [51]:
v1

array([1, 2, 3])

In [47]:
v1.reshape(-1,1).T

array([[1, 2, 3]])

In [48]:
v2.reshape(-1,1)

array([[2],
       [3],
       [4]])

In [49]:
v1.reshape(-1,1).T@v2.reshape(-1,1) # @ : 행렬곱 연산자

array([[20]])

In [52]:
# 중복단어 개수세기
df = df.T
df.sent0.dot(df.sent1)

0

In [53]:
df.sent0.dot(df.sent2)

1

In [54]:
df.sent0.dot(df.sent3)

1

In [55]:
# 내적이 1이되게한 단어를 찾기
[(k,v) for (k,v) in (df.sent0 & df.sent3).items() if v] 

[('moticello', 1)]

In [56]:
(df.sent0 & df.sent3).items() 

In [57]:
(df.sent0 & df.sent3)

thomas          0
jefferson       0
began           0
building        0
moticello       1
at              0
the             0
age             0
of              0
26.             0
construction    0
was             0
done            0
mostly          0
by              0
local           0
masons          0
and             0
carpenters.     0
he              0
moved           0
into            0
south           0
pavilion        0
in              0
1770.           0
turning         0
a               0
neoclassical    0
masterpiece     0
jefferson's     0
obsession.      0
dtype: int64

In [58]:
import re 
sentence = """thomas jefferson began building moticello at the age of 26."""
tokens = re.split(r'[-\s.,;!?]+' , sentence) # 공백이나 몇가지 문장부호를 기준으로 분할함
tokens

#  정규식 파헤치기
# [] : 대괄호는 주어진 텍스트가 부합해야할 문자들의 집합을 지정함
# + : []다음 나오는 + , 주어진 문자 부류의 문자들이 하나이상 부합해야함을 뜻함
# \s : \\t\n\r\f\v 등의 공백문자들을 대표함
# \t 탭
# \r 캐리지 리턴
# \n 새줄
# \f 폼피드
# \v 수직탭 문자
# r'[a-z] , r'[0-9], r'[_a-zA-Z] : 밑줄문자나 영문소문자, 대문자와 부합함
# [-] : 정규 표현식의 까다로운 규칙에 해당함


['thomas',
 'jefferson',
 'began',
 'building',
 'moticello',
 'at',
 'the',
 'age',
 'of',
 '26',
 '']

In [59]:
# 단어 분리를 위한 정규 표현식 개선
pattern = re.compile(r'([-\s.,;:!?])+')
tokens = pattern.split(sentence) 
tokens[-10:]

[' ', 'the', ' ', 'age', ' ', 'of', ' ', '26', '.', '']

In [60]:
sentence = """thomas jefferson began building moticello at the age of 26."""
pattern = re.compile(r'([-\s.,;:!?])+')
tokens = pattern.split(sentence) 
[x for x in tokens if x and x not in '- \t\n.,;!?']

['thomas',
 'jefferson',
 'began',
 'building',
 'moticello',
 'at',
 'the',
 'age',
 'of',
 '26']

In [61]:
# regex : 부합집합중첩, 다중 스레드 적용 유니코드 완벽지원, 근사 정규 표현식 부합, 더큰  maxcache(500개)

In [62]:
# 주요 토큰화 라이브러리 
# spacy : 정확,유연, 빠름, 파이썬
# coreNLP : 스탠퍼드, 더욱 정확하지만 덜 유연, 빠름, JAVA8에 의존
# NLTK : 표준 라이브러리, 유명, 파이썬


In [63]:
from nltk.tokenize import RegexpTokenizer 
tokenizer = RegexpTokenizer(r'\w+|$[0-9.]+|\S+')
tokenizer.tokenize(sentence)

['thomas',
 'jefferson',
 'began',
 'building',
 'moticello',
 'at',
 'the',
 'age',
 'of',
 '26',
 '.']

In [65]:
# 좀더 강력한 토큰화 함수 :  treebandwordtokenizer, 소숫점, 축양형도 토큰화 가능
from nltk.tokenize import TreebankWordTokenizer
sentence = """Monticello wasn't designated as UNESCO World heritage site until 1987."""
tokenizer = TreebankWordTokenizer()

In [67]:
tokenizer.tokenize(sentence)

['Monticello',
 'was',
 "n't",
 'designated',
 'as',
 'UNESCO',
 'World',
 'heritage',
 'site',
 'until',
 '1987',
 '.']

In [77]:
# n-gram을 활용한 어휘 확장
#tokenize_2grams(sentence)

In [78]:
from nltk.util import ngrams
tokens = [x for x in tokens if x and x not in '= \t\n.,;:!?']

list(ngrams(tokens,2))

[('thomas', 'jefferson'),
 ('jefferson', 'began'),
 ('began', 'building'),
 ('building', 'moticello'),
 ('moticello', 'at'),
 ('at', 'the'),
 ('the', 'age'),
 ('age', 'of'),
 ('of', '26')]

In [79]:
list(ngrams(tokens,3))

[('thomas', 'jefferson', 'began'),
 ('jefferson', 'began', 'building'),
 ('began', 'building', 'moticello'),
 ('building', 'moticello', 'at'),
 ('moticello', 'at', 'the'),
 ('at', 'the', 'age'),
 ('the', 'age', 'of'),
 ('age', 'of', '26')]

In [80]:
two_grams = list(ngrams(tokens,2))
[" ".join(x) for x in two_grams]


['thomas jefferson',
 'jefferson began',
 'began building',
 'building moticello',
 'moticello at',
 'at the',
 'the age',
 'age of',
 'of 26']

In [81]:
stop_words = ['a','an','the','on','of','off','this','is']
tokens = ['the','house','is','on','fire'] 
tokens_without_stopwords = [x for x in tokens if x not in stop_words] 
tokens_without_stopwords

['house', 'fire']

In [83]:
# nltk의 불용어 목록
import nltk
nltk.download('stopwords') 
stop_words = nltk.corpus.stopwords.words('english')
len(stop_words)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


179

In [84]:
stop_words[:7]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours']

In [85]:
# 여러 불용어 집합을 같이 사용하기
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS as sklearn_stop_words 
len(sklearn_stop_words)

318

In [86]:
len(stop_words)

179

In [91]:
# len(stop_words.union(sklearn_stop_words))

In [92]:
# len(stop_words.intersection(sklearn_stop_words))

In [93]:
tokens = ['House','Visitors','Center'] 
normalized_tokens = [x.lower() for x in tokens] 
print(normalized_tokens)

['house', 'visitors', 'center']


In [94]:
# 정규화 : 재현율을 높여주지만, 정밀도를 낮춤
# 별로 관심없는 문서들이 검색결과에 포함될 가능성 생김
# 검색엔진을 위한 파이프라인을 구축할때는 두종류의 검색어에 맞는 두종류의 색인을 구축 (정규화 o/x)


In [95]:
# 어간 추출(stemming)
# 영어의 어간추출은 단어들에서 접미사를 제거함으로써 의미가 비슷한 단어들을 하나의 공통어간으로 묶음
# 어간이 반드시 영어사전에 나오는 정확한 철자의 단어일 필요없음
# 어간추출은 문서에 담긴 정보와 의미를 최대한 유지하면서 어휘의 크기를 줄이는 방법
def stem(phrase):
  return ' '.join([re.findall('^(.*ss|.*?)(s)?$', word)[0][0].strip("'") for word in phrase.lower().split()])

  # 만일 단어가 하나의 s로 끝나면 어간은 단어에서 s를 제외한 부분이고 접미사는 S이다
  # 만일 단어가 s로 끝나지 않으면 어간은 그 단어 자체이고 접미사는 없다


In [96]:
stem('houses')

'house'

In [97]:
stem("Doctor House's calls")

'doctor house call'

In [98]:
# 어간추출기
from nltk.stem.porter import PorterStemmer 
stemmer = PorterStemmer() 
' '.join([stemmer.stem(w).strip("'") for w in "dish washer's washed dishes".split()])

'dish washer wash dish'

In [99]:
# 표제어 추출 (lemmatization) 
# 어근수준으로 내려가서 정규화하는것
# 차원축소를 하게 하지만 모형이 덜 정확해지는 단점이 있음
# 뿌리가 같지만 의미가 완전히 같지는 않은 여러 철자변형을 모두 같은 단어로 간주함
# chat, chatter, chatty, chatting을 똑같이 취급
# 단어의 의미를 고려해서 단어들을 정규화한다는 점에서 표제어 추출은 어간추출이나 대소문자 정규화보다 좀더 정확한 정규화 방법이라 할 수있음


In [100]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize("better")  # 명사로 판단

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


'better'

In [101]:
lemmatizer.lemmatize("better",pos="a") 

'good'

In [102]:
lemmatizer.lemmatize("goods", pos="n") 

'good'

In [103]:
lemmatizer.lemmatize("goods", pos="a") 

'goods'

In [104]:
lemmatizer.lemmatize("best", pos="a") 

'best'

In [ ]:
# 일반적으로 어간 추출이 표제어 추출보다 더 빠르고 필요한 코드와 자료집합도 덜 복잡함
# 둘다 어휘의 크기를 줄이는 대신 텍스트의 중의성을 높인다.
